### ISSUE TITLE
JSON error, can t log in.

### ISSUE THREAD

**Issue by Andrejki** [0v3rl0w/Advanced-OSIF#2]
Hi. This may be advanced, but as long as it can t be used, it is useless.
How to fix the log in?

I ve used normal account + the normal password. 
Why am I getting errors while logging in?
JSON is a problem in general?

How to fix this?

Thank you on this share sincerely, but unless it doesn t work, it is really useless for anyone?
Looking forward to hearing your answer and fix.
Kind regards 

```
Traceback (most recent call last):
  File "osif.py", line 149, in <module>
    token = create_token(token)
  File "osif.py", line 97, in create_token
    token = get_token(username, password)
  File "osif.py", line 84, in get_token
    return json_data['access_token']
KeyError: 'access_token'
```

**Comment by keyboard-slayer** [comment]
Hi, thanks for giving attention to my project.
That project doesn't really work anymore, I wrote it back in 2019 and seems like Facebook have tighten their security policy. 
The login seems fixable to me but every other features of this script won't work anymore.

Hope you'll find an alternative for your need  :smile:
